### ISSUE TITLE
404

### ISSUE THREAD

**Issue by junxuny** [qunarcorp/startalk_node#5]
http://127.0.0.1:5002/newapi/domain/get_vcard_info.qunar

**Comment by junxuny** [comment]
http://127.0.0.1:5002/newapi/update/getUpdateUsers.qunar

**Comment by junxuny** [comment]
http://127.0.0.1:5002/newapi/domain/get_vcard_info.qunar
http://127.0.0.1:5002/package/qtapi/getrbl.qunar

**Comment by may-liu** [comment]
看起来像是没配置对

请参考这一节：

![1](https://user-images.githubusercontent.com/5277672/55399028-996eec80-557c-11e9-9092-6116d0471a09.png)

另外从报错上来看，感觉端口改成8080就可以了，默认没有5002这个端口

**Comment by junxuny** [comment]
module.exports = {
    "domain":"qtalk.test.org",
    "pub_key_fullkey": "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCy2VXDAlCZlj7gPHvC/vwvbpTN\n/GyW0tmNCqh0UPitdTTGZk3UcLqu9lWMGPViL/5lhboiSogsDxJLHdwo91DDBjTX\n1HbuyuOhvsvayV7Yc8t+ajFW/8RwlvhGSzVplthoU+md9kGeZ8t73VWWZUEB0iyW\nx7Y/RjUwTdnOlNXDzQIDAQAB\n-----END PUBLIC KEY-----",
    "fileurl":"http://192.168.10.165:8080",
    "javaurl":"http://192.168.10.165:8080/package",
    "httpurl":"http://192.168.10.165:8080/newapi",
    "apiurl":"http://192.168.10.165:8080/api",
    "searchurl":"http://192.168.10.165:8080/search/search.py"
}

**Comment by junxuny** [comment]
我这样配置的，我观察到浏览器报404错

**Comment by junxuny** [comment]
![image](https://user-images.githubusercontent.com/4536052/55447085-e5f60e80-55f4-11e9-8410-5509592aaba0.png)

**Comment by junxuny** [comment]
这个是 node_web项目

**Comment by code-lynn** [comment]
请参考部署策略中第五小节：
![image](https://user-images.githubusercontent.com/21981393/55713731-d9721b80-5a23-11e9-90ca-02d0bd1ce123.png)
在服务器部署完成并且启动成功后，浏览器输入您部署的服务器IP+端口访问。
截图中localhost访问不到接口数据是因为本地电脑的localhost服务并没有部署接口的服务，应输入已经部署后台服务的机器IP+端口访问。
